<a href="https://colab.research.google.com/github/IsraelPanazollo/Problema_de_Classificacao/blob/main/Aplicacao_Classificacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***
# <font color=green size=10>APLICAÇÃO DE CLASSIFICAÇÃO</font>
***

# Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

## Verificação das versões

In [2]:
print('Versão do pandas -> %s' % pd.__version__)
print('Versão do numpy -> %s' % np.__version__)
print('Versão do seaborn -> %s' % sns.__version__)
print('Versão do sklearn -> %s' % sklearn.__version__)

Versão do pandas -> 2.0.3
Versão do numpy -> 1.25.2
Versão do seaborn -> 0.13.1
Versão do sklearn -> 1.2.2


# Exploração dos dados

Segundo a fonte original, o Kaggle, as características V1 a V28, são resultados de uma transformação PCA, não sendo possível saber mais detalhes. O tempo diz respeito a quantos segundos se passaram entre a primeira transações e as outras. O amount apresenta a quantia da transação. Por fim, temos o rótulo na Class, que indica se é ou não uma fraude.

## Importação dos dados

In [3]:
dados = pd.read_csv('creditcard.csv')

In [4]:
dados.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

Daremos uma olhada nos registros que foram classificados como fraude.

In [5]:
dados.query('Class == 1').head()

Time        V1        V2        V3        V4        V5        V6  \
541    406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545   
623    472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823   
4920  4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788   
6108  6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536   
6329  7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746   

            V7        V8        V9  ...       V21       V22       V23  \
541  -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211   
623   0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966   
4920  0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726   
6108 -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207   
6329  1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805   

           V24       V25       V26       V27       V28  Amount  Class  
541   0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1  
623  -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1  
4920 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1  
6108 -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1  
6329 -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1  

[5 rows x 31 columns]

## Verificação das informações

Dada a importância de conhecer os dados, obtem-se o número de registros e campos, além da verificação da presença de valores ausentes, além do tipo de dados nas colunas.

In [6]:
dados.shape

(284807, 31)

In [7]:
dados.isna().sum().sum()

0

In [8]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

À partir dos registros, podemos constatar o número de transações e o número de fraudes assinaladas

In [9]:
n_transacoes = dados['Class'].count()
n_fraudes = dados['Class'].sum()
proporcao = n_fraudes / n_transacoes

print("Número de transações: ", n_transacoes)
print("Número de fraudes: ", n_fraudes)
print(f"A proporção de fraudes em relações as transações é {round(proporcao*100,3)}%")

Número de transações:  284807
Número de fraudes:  492
A proporção de fraudes em relações as transações é 0.173%


# Classificação

Deseja-se obter um modelo que realiza a classificação das transações como fraudulentas ou não. Para tanto serão aplicados diferentes modelos e será escolhido o melhor.

## Preparação para a modelagem

Antes de utilizar os dados nos modelos, vamos realizar a separação em dados de treino e teste de modo estratificado, uma vez que há uma proporção muito baixa de transações classificadas como fraude. Foi retirado o campo time, uma vez que este funciona como uma identificação com relação a primeira transação

### Separação do conjunto

In [10]:
seed = 42
np.random.seed(seed)

In [11]:
X = dados.drop(['Time','Class'], axis=1)
y = dados['Class']

In [12]:
from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(X,y,test_size = 0.3, random_state = seed, stratify=y)

### Pré-processamento para alguns modelos

Os modelos LinearSVC e SVC são sensíveis a escala dos dados, portanto, utiliza-se um escalador para padronizar os dados, isto é, tornar a média zero e o desvio padrão um.

In [13]:
from sklearn.preprocessing import StandardScaler

escalador = StandardScaler()
escalador.fit(X_treino)
X_treino_escalado = escalador.transform(X_treino)
X_teste_escalado = escalador.transform(X_teste)

### Definição das funções para executar as funções e verificar as métricas

Para evitar a repetição de código serão criadas as funções para executar os classificadores e obter as predições das classes. Além de uma função para apresentar as principais métricas dos modelos de classificação.

In [14]:
def executar_classificador(classificador):
  modelo = classificador
  modelo.fit(X_treino, y_treino)
  y_predito = modelo.predict(X_teste)
  return y_predito

In [15]:
def executar_classificador_escalado(classificador):
  modelo = classificador
  modelo.fit(X_treino_escalado, y_treino)
  y_predito = modelo.predict(X_teste_escalado)
  return y_predito

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

def validar_classificador(y_predito):
  print("A acurácia do modelo é: ", round(accuracy_score(y_teste, y_predito),3))
  print("A precisão do modelo é: ", round(precision_score(y_teste, y_predito),3))
  print("A sensibilidade do modelo é: ", round(recall_score(y_teste, y_predito),3))
  print("O f1 score do modelo é: ", round(f1_score(y_teste, y_predito),3))
  print("A matriz de confusão do modelo é: \n", confusion_matrix(y_teste, y_predito))

## Modelos de classificação

### Classificador bobo

O classificado bobo é usado para termos uma linha de base para quão bom é o classificador em questão. Nesse caso, por padrão o DummyClassifier dirá que todas as predições são não fraudulentas, dado que a frequência destas é muito maior. Daqui fica claro que atentar apenas para a acurácia não é uma boa estratégia.

In [17]:
from sklearn.dummy import DummyClassifier

Dummy = DummyClassifier()
Dummy_predito = executar_classificador(DummyClassifier())
validar_classificador(Dummy_predito)

A acurácia do modelo é:  0.998
A precisão do modelo é:  0.0
A sensibilidade do modelo é:  0.0
O f1 score do modelo é:  0.0
A matriz de confusão do modelo é: 
 [[85295     0]
 [  148     0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### SVC Linear

Utilizando a support vector machine linear para classificação, nota-se que a melhor resposta é de fato aquela com os dados escalados, com um modelo com boa precisão e sensibilidade.

In [18]:
from sklearn.svm import LinearSVC

LSVC = LinearSVC()
LSVC_predito = executar_classificador(LSVC)
validar_classificador(LSVC_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.867
A sensibilidade do modelo é:  0.75
O f1 score do modelo é:  0.804
A matriz de confusão do modelo é: 
 [[85278    17]
 [   37   111]]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [19]:
LSVC = LinearSVC()
LSVC_predito = executar_classificador_escalado(LSVC)
validar_classificador(LSVC_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.85
A sensibilidade do modelo é:  0.649
O f1 score do modelo é:  0.736
A matriz de confusão do modelo é: 
 [[85278    17]
 [   52    96]]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


### SVC

A support vector machine para classificaçaõ permite lidar com não linearidades, daqui vemos que o modelo obteve uma excelente performance com relação a precisão.

In [20]:
from sklearn.svm import SVC

SVC = SVC()
SVC_predito = executar_classificador(SVC)
validar_classificador(SVC_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.769
A sensibilidade do modelo é:  0.338
O f1 score do modelo é:  0.469
A matriz de confusão do modelo é: 
 [[85280    15]
 [   98    50]]


In [21]:
from sklearn.svm import SVC

SVC = SVC()
SVC_predito = executar_classificador_escalado(SVC)
validar_classificador(SVC_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.967
A sensibilidade do modelo é:  0.601
O f1 score do modelo é:  0.742
A matriz de confusão do modelo é: 
 [[85292     3]
 [   59    89]]


### Árvore de Decisão

A árvore de decisão também é um classificador muito conhecido, a qual obteve um bom escore na precisão e sensibilidade no modelo.

In [22]:
from sklearn.tree import DecisionTreeClassifier

DTR = DecisionTreeClassifier()
DTR_predito = executar_classificador(DTR)
validar_classificador(DTR_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.805
A sensibilidade do modelo é:  0.723
O f1 score do modelo é:  0.762
A matriz de confusão do modelo é: 
 [[85269    26]
 [   41   107]]


Podemos agrupar várias árvores de decisão em conjunto, as quais podem dar um resultado combinado melhor na classificação do que apenas uma árvore. Dos resultados vemos uma ótima precisão e uma boa sensibilidade, visto especialmente pelo f1 score.

In [23]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier()
RFC_predito = executar_classificador(RFC)
validar_classificador(RFC_predito)

A acurácia do modelo é:  1.0
A precisão do modelo é:  0.957
A sensibilidade do modelo é:  0.757
O f1 score do modelo é:  0.845
A matriz de confusão do modelo é: 
 [[85290     5]
 [   36   112]]


Outra maneira das árvores de decisão trabalhar em conjunto é através de um modelo sequencial, no qual uma árvore ajusta outra, oferecendo um resultado final mais preciso. De fato, o resultado deste grupo foi melhor do que apenas uma árvore de decisão.

In [24]:
from sklearn.ensemble import AdaBoostClassifier

ABC = AdaBoostClassifier()
ABC_predito = executar_classificador(ABC)
validar_classificador(ABC_predito)

A acurácia do modelo é:  0.999
A precisão do modelo é:  0.761
A sensibilidade do modelo é:  0.73
O f1 score do modelo é:  0.745
A matriz de confusão do modelo é: 
 [[85261    34]
 [   40   108]]


# Escolha do modelo

Frente aos resultados dos diferentes modelos, aquele que possui melhores métricas é a floresta aleatória. As seguintes considerações são válidas de destacar:

* A precisão elevada significa que o modelo não classificará como fraude aquelas transações que deveriam ser normais, isto é, terá poucos falsos positivos. Ter isso é importante para que os clientes não reclamem de bloquear transações que eles mesmos fizeram.

$$ Precisao = \frac{VP}{VP+FP} $$

* A sensibilidade/recall elevada indica que o modelo classificará como fraude aquelas transações que deveriam ser classificadas como fraudes, ou seja, terá poucos falsos negativos. Ter isso é importante para que os clientes não reclamem de transações suspeitas no seu cartão e o banco não fazer nada.

$$ Sensibilidade = \frac{VP}{VP+FN} $$

* Um escore bom de f1 significa que a relação entre precisão e sensibilidade está boa.

### Teste do modelo

In [25]:
transacao_teste = pd.DataFrame({
    "V1":[-0.533414],
    "V2":[-0.189734],
    "V3":[0.703338],
    "V4":[-0.506272],
    "V5":[-0.012547],
    "V6":[-0.649618],
    "V7":[1.577007],
    "V8":[-0.414651],
    "V9":[0.486181],
    "V10":[-0.915428],
    "V11":[-1.040459],
    "V12":[-0.031514],
    "V13":[-0.188094],
    "V14":[-0.084317],
    "V15":[0.041334],
    "V16":[-0.302621],
    "V17":[-0.660378],
    "V18":[0.167431],
    "V19":[-0.256118],
    "V20":[0.382949],
    "V21":[0.261058],
    "V22":[0.643079],
    "V23":[0.376778],
    "V24":[0.008798],
    "V25":[-0.473650],
    "V26":[-0.818268],
    "V27":[-0.002416],
    "V28":[0.013650],
    "Amount":[220.000000]
})

In [26]:
predicao = RFC.predict(transacao_teste)
if predicao == 1:
  print("A transação foi classificada como fraudulenta")
else:
  print("A transição foi classificada como normal")

A transição foi classificada como normal


## Armazenar o modelo

In [27]:
import pickle
output = open('modelo', 'wb')
pickle.dump(RFC, output)
output.close()